export const root: string;
export const imagewrap: string;
export const cardshaped: string;
export const content: string;
export const imagecaption: string;
export const image: string;
export const cardwide: string;
export const cardwideimagewrap: string;
export const fontsize1: string;
